version: '2.0'

services:
    dispatcher:
        build: ./docker/dispatcher
        image: ${CONTAINER_NAME_PREFIX}/dispatcher
        container_name: dispatcher
        ports:
            - 8000
        networks:
            private:
                aliases:
                    - dispatcher
        depends_on:
            - app
    app:
        build: ./docker/app
        image: ${CONTAINER_NAME_PREFIX}/${CURRENT_BRANCH}
        container_name: ${CURRENT_BRANCH}
        networks:
            private:
                aliases:
                    - ${CURRENT_BRANCH}
        depends_on:
            - db
        volumes:
            - "${PWD}/node_modules:/usr/src/${CURRENT_BRANCH}/node_modules"
    db:
        build: ./docker/db
        image: ${CONTAINER_NAME_PREFIX}/db
        container_name: db
        volumes:
            - ${PWD}/mysql:/var/lib/mysql
        networks:
            private:
                aliases:
                    - nouns_db
                    - verbs_db
                    - adjectives_db
                    - db
networks:
    private:
        external: true